name: Manual Deploy to EC2

on:
  workflow_dispatch:
    inputs:
      deployment_message:
        description: 'Deployment Message'
        required: false
        default: 'Manual deployment triggered'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Create SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key.pem
        chmod 600 ~/.ssh/deploy_key.pem
        
    - name: Create .dockerignore
      run: |
        echo "node_modules" > .dockerignore
        echo ".git" >> .dockerignore
        echo ".env*" >> .dockerignore
        
    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no \
          -r ./* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USERNAME }}/app/

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/deploy_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
          cd /home/${{ secrets.SSH_USERNAME }}/app
          if [ ! -f .env_backend ]; then
            echo "Error: .env_backend file not found!"
            exit 1
          fi
          docker compose down
          docker compose up --build -d
        '

    - name: Cleanup
      if: always()
      run: rm -f ~/.ssh/deploy_key.pem